version: '3.4'

services:
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    environment: 
      DB_CONNECTION_STRING: Server=auth-database;Database=authentication;User=sa;Password=P@ssword;TrustServerCertificate=True;

  auth-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword
    ports:
      - "1433:1433"
    volumes:
      - "auth-service:/var/opt/mssql"

volumes:
  auth-service:

